[package]
name = "rs4a-vapix"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
url = { workspace = true }
